pipeline {
    agent {
        label 'master'
    }
    environment {
        tokenLineF = 'KU7zIs892MzQrur12rZSsEQCxGyDtHFEWDQiyir87zv'
        PATH = '/home/ec2-user/script/front/:$PATH'

    }
    stages {
        
         stage('prepare') {
            steps {
                echo 'prepare build'
                git branch: 'main', url: 'https://github.com/charatkosit/go-template.git'
                withEnv(['PATH+EXTRA=/usr/sbin:/usr/bin:/sbin:/bin']) {
                sh 'chmod +x -R ${env.WORKSPACE}'
                sh '. envFrontWithUAT.sh'
                // sh 'curl -X POST -H "Authorization: Bearer ${tokenLineF}" -F "message=UAT prepare Code OK" https://notify-api.line.me/api/notify'
                }
            }
        }
        
        stage('Build') {
            steps {
                echo 'Build Docker step'
                sh '. build-front-uat.sh'
                // sh 'curl -X POST -H "Authorization: Bearer ${tokenLineF}" -F "message=UAT build Code Ok" https://notify-api.line.me/api/notify'
               
                
                
            }
        }
        stage('Push to DockerHub') {
            steps {
                echo 'Testing..'
                sh 'docker login -u "charat" -p "Do#5898791"'
                sh '. dockerPush-front-uat.sh'
                // sh 'curl -X POST -H "Authorization: Bearer ${tokenLineF}" -F "message=UAT push DockerHub OK" https://notify-api.line.me/api/notify'
               
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy..'
            }
        }
    }
}