pipeline {
    agent {
        label 'master'
    }
    environment {
        tokenLineB = 'jK01GQRfcbCkrExb8euztYLqB1WpDgMhIIR1pah5OCH'
    }
    stages {
        
         stage('prepare') {
            steps {
                echo 'prepare build'
                git branch: 'main', url: 'https://github.com/charatkosit/go-back.git'
                sh '. /home/ec2-user/script/back/envBackWithUAT-v1.sh'
                sh 'curl -X POST -H "Authorization: Bearer ${tokenLineB}" -F "message=UAT prepare Code" https://notify-api.line.me/api/notify'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Build Docker step'
                sh '. /home/ec2-user/script/back/build-back-uat.sh'
                sh 'curl -X POST -H "Authorization: Bearer ${tokenLineB}" -F "message=UAT build Code OK" https://notify-api.line.me/api/notify'
               
                
                
            }
        }
        stage('Push to DockerHub') {
            steps {
                echo 'Testing..'
                sh 'docker login -u "charat" -p "Do#5898791"'
                sh '. /home/ec2-user/script/back/dockerPush-back-uat.sh'
                sh 'curl -X POST -H "Authorization: Bearer ${tokenLineB}" -F "message=UAT push DockerHub OK" https://notify-api.line.me/api/notify'

               
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy..'
            }
        }
    }
}