pipeline {
    agent {
        label 'master'
    }
    environment {
        tokenLineF = 'KU7zIs892MzQrur12rZSsEQCxGyDtHFEWDQiyir87zv'

    }
    stages {
        
         stage('prepare') {
            steps {
                echo 'prepare build'
                git branch: 'main', url: 'https://github.com/charatkosit/go-template.git'
                sh '. /home/ec2-user/script/front/envFrontWithSIT.sh'
                sh 'curl -X POST -H "Authorization: Bearer ${tokenLineF}" -F "message=SIT prepare Code OK" https://notify-api.line.me/api/notify'
            }
        }
        
        stage('Build') {
            steps {
                echo 'Build Docker step'
                sh '. /home/ec2-user/script/front/build-front-sit.sh'
                sh 'curl -X POST -H "Authorization: Bearer ${tokenLineF}" -F "message=SIT build Code OK" https://notify-api.line.me/api/notify'
               
                
                
            }
        }
        stage('Push to DockerHub') {
            steps {
                echo 'Testing..'
                sh 'docker login -u "charat" -p "Do#5898791"'
                sh '. /home/ec2-user/script/front/dockerPush-front-sit.sh'
                sh 'curl -X POST -H "Authorization: Bearer ${tokenLineF}" -F "message=SIT push DockerHub OK" https://notify-api.line.me/api/notify'
               
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploy..'
            }
        }
        stage ('Invoke go-front-uat') {
            steps {
                build job: 'go-front-uat', parameters: [
                string(name: 'param1', value: "value1")
                ]
            }
        }
    }
}